version: '2.1'

networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.255.0/24
      driver: default

services:
  kafka:                                                                                                                       
    image: wurstmeister/kafka:2.12-2.1.0
    mem_limit: 1024m
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      main:
 
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    mem_limit: 450m
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper
    networks:
      main:

  gw:
    image: "gw:latest"
    restart: always
    ports:
      - "8080:8080"
    expose:
      - "8080"
    build:
      dockerfile: apigw/Dockerfile
      context: .
    depends_on:
      - kafka
    command: "./api-gw"
    networks:
      main:

  ui:
    image: "ui:latest"
    restart: always
    ports:
      - "9091:80"
    expose:
      - "9091"
    build:
      dockerfile: ui/Dockerfile
      context: .
    depends_on:
      - gw
    command: 'nginx -g "daemon off;"'
    networks:
      main:
