---
version: "3.7"
networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.255.0/24
      driver: default

services:
  kafka:                                                                                                                       
    image: wurstmeister/kafka:2.12-2.1.0
    mem_limit: 1024m
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      main:
 
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    mem_limit: 512m
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper
    networks:
      main:

  postgres:
    image: "postgres:alpine"
    restart: always
    tmpfs:
      - /var/lib/postgresql/data
    environment:
        POSTGRES_USER: "${POSTGRESQL_USER}"
        POSTGRES_PASSWORD: "${POSTGRESQL_PASS}"
    ports:
        - "${POSTGRESQL_PORT}:${POSTGRESQL_PORT}"
    expose:
        - "${POSTGRESQL_PORT}"
    networks:
        main:
            ipv4_address: ${POSTGRESQL_IP}

  gw:
    image: "gw:latest"
    restart: always
    ports:
      - "9093:8080"
    build:
      dockerfile: apigw/Dockerfile
      context: .
    depends_on:
      - kafka
      - postgres
    command: "./api-gw --host 0.0.0.0"
    networks:
      main:

  ui:
    image: "ui:latest"
    restart: always
    ports:
      - "9091:80"
    build:
      dockerfile: ui/Dockerfile
      context: .
    depends_on:
      - gw
    command: 'nginx -g "daemon off;"'
    networks:
      main:
